# MAIN URLS
POSSERVER = "https://posserver01"
MWS_PAGE_URL = f"{POSSERVER}:7495"
POS_PAGE_URL = f"{POSSERVER}:7501"

# MWS URLS
DISCOUNTS_PAGE_URL = f"{MWS_PAGE_URL}/DiscountMaintenance"
ITEMS_PAGE_URL = f"{MWS_PAGE_URL}/Item"
PDL_DOWNLOAD_PAGE_URL = f"{MWS_PAGE_URL}/NetworkService/23/1009"
STORE_CLOSE_PAGE_URL = f"{MWS_PAGE_URL}/StoreClose"
FORECOURT_INSTALLATION_PAGE_URL = f"{MWS_PAGE_URL}/ForecourtInstallation"
REGISTERS_PAGE_URL = f"{MWS_PAGE_URL}/RegisterSetup"
TENDERS_PAGE_URL = f"{MWS_PAGE_URL}/TenderMaintenancePage"
LOYALTY_PAGE_URL = f"{MWS_PAGE_URL}/LoyaltyConfiguration"
NETWORK_CONFIGURATION_PAGE_URL = f"{MWS_PAGE_URL}/NetworkConfiguration/23/1"
