# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import libs.grpc.resources.compiled_protos.CarWash_pb2 as CarWash__pb2


class CarWashServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCarwashPackageNames = channel.unary_unary(
                '/CarWashService/GetCarwashPackageNames',
                request_serializer=CarWash__pb2.GetCarwashPackageNamesRequest.SerializeToString,
                response_deserializer=CarWash__pb2.GetCarwashPackageNamesReply.FromString,
                )
        self.GetCarWashConfiguration = channel.unary_unary(
                '/CarWashService/GetCarWashConfiguration',
                request_serializer=CarWash__pb2.GetCarWashConfigurationRequest.SerializeToString,
                response_deserializer=CarWash__pb2.GetCarWashConfigurationReply.FromString,
                )
        self.SetCarWashConfiguration = channel.unary_unary(
                '/CarWashService/SetCarWashConfiguration',
                request_serializer=CarWash__pb2.SetCarWashConfigurationRequest.SerializeToString,
                response_deserializer=CarWash__pb2.SetCarWashConfigurationReply.FromString,
                )
        self.SetCarwashEnabled = channel.unary_unary(
                '/CarWashService/SetCarwashEnabled',
                request_serializer=CarWash__pb2.SetCarwashEnabledRequest.SerializeToString,
                response_deserializer=CarWash__pb2.SetCarwashEnabledReply.FromString,
                )


class CarWashServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCarwashPackageNames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCarWashConfiguration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCarWashConfiguration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCarwashEnabled(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CarWashServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCarwashPackageNames': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCarwashPackageNames,
                    request_deserializer=CarWash__pb2.GetCarwashPackageNamesRequest.FromString,
                    response_serializer=CarWash__pb2.GetCarwashPackageNamesReply.SerializeToString,
            ),
            'GetCarWashConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCarWashConfiguration,
                    request_deserializer=CarWash__pb2.GetCarWashConfigurationRequest.FromString,
                    response_serializer=CarWash__pb2.GetCarWashConfigurationReply.SerializeToString,
            ),
            'SetCarWashConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCarWashConfiguration,
                    request_deserializer=CarWash__pb2.SetCarWashConfigurationRequest.FromString,
                    response_serializer=CarWash__pb2.SetCarWashConfigurationReply.SerializeToString,
            ),
            'SetCarwashEnabled': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCarwashEnabled,
                    request_deserializer=CarWash__pb2.SetCarwashEnabledRequest.FromString,
                    response_serializer=CarWash__pb2.SetCarwashEnabledReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CarWashService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CarWashService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCarwashPackageNames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CarWashService/GetCarwashPackageNames',
            CarWash__pb2.GetCarwashPackageNamesRequest.SerializeToString,
            CarWash__pb2.GetCarwashPackageNamesReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCarWashConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CarWashService/GetCarWashConfiguration',
            CarWash__pb2.GetCarWashConfigurationRequest.SerializeToString,
            CarWash__pb2.GetCarWashConfigurationReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetCarWashConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CarWashService/SetCarWashConfiguration',
            CarWash__pb2.SetCarWashConfigurationRequest.SerializeToString,
            CarWash__pb2.SetCarWashConfigurationReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetCarwashEnabled(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CarWashService/SetCarwashEnabled',
            CarWash__pb2.SetCarwashEnabledRequest.SerializeToString,
            CarWash__pb2.SetCarwashEnabledReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
