# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import libs.grpc.resources.compiled_protos.FuelDiscounts_pb2 as FuelDiscounts__pb2


class FuelDiscountsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetManualFuelDiscounts = channel.unary_unary(
                '/FuelDiscounts/GetManualFuelDiscounts',
                request_serializer=FuelDiscounts__pb2.GetManualFuelDiscountsRequest.SerializeToString,
                response_deserializer=FuelDiscounts__pb2.GetManualFuelDiscountsReply.FromString,
                )
        self.AddManualFuelDiscount = channel.unary_unary(
                '/FuelDiscounts/AddManualFuelDiscount',
                request_serializer=FuelDiscounts__pb2.AddManualFuelDiscountRequest.SerializeToString,
                response_deserializer=FuelDiscounts__pb2.AddManualFuelDiscountReply.FromString,
                )
        self.UpdateManualFuelDiscount = channel.unary_unary(
                '/FuelDiscounts/UpdateManualFuelDiscount',
                request_serializer=FuelDiscounts__pb2.UpdateManualFuelDiscountRequest.SerializeToString,
                response_deserializer=FuelDiscounts__pb2.UpdateManualFuelDiscountReply.FromString,
                )
        self.DeleteManualFuelDiscount = channel.unary_unary(
                '/FuelDiscounts/DeleteManualFuelDiscount',
                request_serializer=FuelDiscounts__pb2.DeleteManualFuelDiscountRequest.SerializeToString,
                response_deserializer=FuelDiscounts__pb2.DeleteManualFuelDiscountReply.FromString,
                )
        self.GetCashFuelDiscounts = channel.unary_unary(
                '/FuelDiscounts/GetCashFuelDiscounts',
                request_serializer=FuelDiscounts__pb2.GetCashFuelDiscountsRequest.SerializeToString,
                response_deserializer=FuelDiscounts__pb2.GetCashFuelDiscountsReply.FromString,
                )
        self.AddCashFuelDiscount = channel.unary_unary(
                '/FuelDiscounts/AddCashFuelDiscount',
                request_serializer=FuelDiscounts__pb2.AddCashFuelDiscountRequest.SerializeToString,
                response_deserializer=FuelDiscounts__pb2.AddCashFuelDiscountReply.FromString,
                )
        self.UpdateCashFuelDiscount = channel.unary_unary(
                '/FuelDiscounts/UpdateCashFuelDiscount',
                request_serializer=FuelDiscounts__pb2.UpdateCashFuelDiscountRequest.SerializeToString,
                response_deserializer=FuelDiscounts__pb2.UpdateCashFuelDiscountReply.FromString,
                )
        self.DeleteCashFuelDiscount = channel.unary_unary(
                '/FuelDiscounts/DeleteCashFuelDiscount',
                request_serializer=FuelDiscounts__pb2.DeleteCashFuelDiscountRequest.SerializeToString,
                response_deserializer=FuelDiscounts__pb2.DeleteCashFuelDiscountReply.FromString,
                )
        self.GetFuelDiscountGroups = channel.unary_unary(
                '/FuelDiscounts/GetFuelDiscountGroups',
                request_serializer=FuelDiscounts__pb2.GetFuelDiscountGroupsRequest.SerializeToString,
                response_deserializer=FuelDiscounts__pb2.GetFuelDiscountGroupsReply.FromString,
                )
        self.AddFuelDiscountGroup = channel.unary_unary(
                '/FuelDiscounts/AddFuelDiscountGroup',
                request_serializer=FuelDiscounts__pb2.AddFuelDiscountGroupRequest.SerializeToString,
                response_deserializer=FuelDiscounts__pb2.AddFuelDiscountGroupReply.FromString,
                )
        self.UpdateFuelDiscountGroup = channel.unary_unary(
                '/FuelDiscounts/UpdateFuelDiscountGroup',
                request_serializer=FuelDiscounts__pb2.UpdateFuelDiscountGroupRequest.SerializeToString,
                response_deserializer=FuelDiscounts__pb2.UpdateFuelDiscountGroupReply.FromString,
                )
        self.DeleteFuelDiscountGroup = channel.unary_unary(
                '/FuelDiscounts/DeleteFuelDiscountGroup',
                request_serializer=FuelDiscounts__pb2.DeleteFuelDiscountGroupRequest.SerializeToString,
                response_deserializer=FuelDiscounts__pb2.DeleteFuelDiscountGroupReply.FromString,
                )
        self.GetCarwashFuelDiscounts = channel.unary_unary(
                '/FuelDiscounts/GetCarwashFuelDiscounts',
                request_serializer=FuelDiscounts__pb2.GetCarwashFuelDiscountsRequest.SerializeToString,
                response_deserializer=FuelDiscounts__pb2.GetCarwashFuelDiscountsReply.FromString,
                )
        self.AddCarwashFuelDiscount = channel.unary_unary(
                '/FuelDiscounts/AddCarwashFuelDiscount',
                request_serializer=FuelDiscounts__pb2.AddCarwashFuelDiscountRequest.SerializeToString,
                response_deserializer=FuelDiscounts__pb2.AddCarwashFuelDiscountReply.FromString,
                )
        self.UpdateCarwashFuelDiscount = channel.unary_unary(
                '/FuelDiscounts/UpdateCarwashFuelDiscount',
                request_serializer=FuelDiscounts__pb2.UpdateCarwashFuelDiscountRequest.SerializeToString,
                response_deserializer=FuelDiscounts__pb2.UpdateCarwashFuelDiscountReply.FromString,
                )
        self.DeleteCarwashFuelDiscount = channel.unary_unary(
                '/FuelDiscounts/DeleteCarwashFuelDiscount',
                request_serializer=FuelDiscounts__pb2.DeleteCarwashFuelDiscountRequest.SerializeToString,
                response_deserializer=FuelDiscounts__pb2.DeleteCarwashFuelDiscountReply.FromString,
                )


class FuelDiscountsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetManualFuelDiscounts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddManualFuelDiscount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateManualFuelDiscount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteManualFuelDiscount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCashFuelDiscounts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddCashFuelDiscount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCashFuelDiscount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCashFuelDiscount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFuelDiscountGroups(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddFuelDiscountGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateFuelDiscountGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFuelDiscountGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCarwashFuelDiscounts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddCarwashFuelDiscount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCarwashFuelDiscount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCarwashFuelDiscount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FuelDiscountsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetManualFuelDiscounts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetManualFuelDiscounts,
                    request_deserializer=FuelDiscounts__pb2.GetManualFuelDiscountsRequest.FromString,
                    response_serializer=FuelDiscounts__pb2.GetManualFuelDiscountsReply.SerializeToString,
            ),
            'AddManualFuelDiscount': grpc.unary_unary_rpc_method_handler(
                    servicer.AddManualFuelDiscount,
                    request_deserializer=FuelDiscounts__pb2.AddManualFuelDiscountRequest.FromString,
                    response_serializer=FuelDiscounts__pb2.AddManualFuelDiscountReply.SerializeToString,
            ),
            'UpdateManualFuelDiscount': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateManualFuelDiscount,
                    request_deserializer=FuelDiscounts__pb2.UpdateManualFuelDiscountRequest.FromString,
                    response_serializer=FuelDiscounts__pb2.UpdateManualFuelDiscountReply.SerializeToString,
            ),
            'DeleteManualFuelDiscount': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteManualFuelDiscount,
                    request_deserializer=FuelDiscounts__pb2.DeleteManualFuelDiscountRequest.FromString,
                    response_serializer=FuelDiscounts__pb2.DeleteManualFuelDiscountReply.SerializeToString,
            ),
            'GetCashFuelDiscounts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCashFuelDiscounts,
                    request_deserializer=FuelDiscounts__pb2.GetCashFuelDiscountsRequest.FromString,
                    response_serializer=FuelDiscounts__pb2.GetCashFuelDiscountsReply.SerializeToString,
            ),
            'AddCashFuelDiscount': grpc.unary_unary_rpc_method_handler(
                    servicer.AddCashFuelDiscount,
                    request_deserializer=FuelDiscounts__pb2.AddCashFuelDiscountRequest.FromString,
                    response_serializer=FuelDiscounts__pb2.AddCashFuelDiscountReply.SerializeToString,
            ),
            'UpdateCashFuelDiscount': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCashFuelDiscount,
                    request_deserializer=FuelDiscounts__pb2.UpdateCashFuelDiscountRequest.FromString,
                    response_serializer=FuelDiscounts__pb2.UpdateCashFuelDiscountReply.SerializeToString,
            ),
            'DeleteCashFuelDiscount': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCashFuelDiscount,
                    request_deserializer=FuelDiscounts__pb2.DeleteCashFuelDiscountRequest.FromString,
                    response_serializer=FuelDiscounts__pb2.DeleteCashFuelDiscountReply.SerializeToString,
            ),
            'GetFuelDiscountGroups': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFuelDiscountGroups,
                    request_deserializer=FuelDiscounts__pb2.GetFuelDiscountGroupsRequest.FromString,
                    response_serializer=FuelDiscounts__pb2.GetFuelDiscountGroupsReply.SerializeToString,
            ),
            'AddFuelDiscountGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.AddFuelDiscountGroup,
                    request_deserializer=FuelDiscounts__pb2.AddFuelDiscountGroupRequest.FromString,
                    response_serializer=FuelDiscounts__pb2.AddFuelDiscountGroupReply.SerializeToString,
            ),
            'UpdateFuelDiscountGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateFuelDiscountGroup,
                    request_deserializer=FuelDiscounts__pb2.UpdateFuelDiscountGroupRequest.FromString,
                    response_serializer=FuelDiscounts__pb2.UpdateFuelDiscountGroupReply.SerializeToString,
            ),
            'DeleteFuelDiscountGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFuelDiscountGroup,
                    request_deserializer=FuelDiscounts__pb2.DeleteFuelDiscountGroupRequest.FromString,
                    response_serializer=FuelDiscounts__pb2.DeleteFuelDiscountGroupReply.SerializeToString,
            ),
            'GetCarwashFuelDiscounts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCarwashFuelDiscounts,
                    request_deserializer=FuelDiscounts__pb2.GetCarwashFuelDiscountsRequest.FromString,
                    response_serializer=FuelDiscounts__pb2.GetCarwashFuelDiscountsReply.SerializeToString,
            ),
            'AddCarwashFuelDiscount': grpc.unary_unary_rpc_method_handler(
                    servicer.AddCarwashFuelDiscount,
                    request_deserializer=FuelDiscounts__pb2.AddCarwashFuelDiscountRequest.FromString,
                    response_serializer=FuelDiscounts__pb2.AddCarwashFuelDiscountReply.SerializeToString,
            ),
            'UpdateCarwashFuelDiscount': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCarwashFuelDiscount,
                    request_deserializer=FuelDiscounts__pb2.UpdateCarwashFuelDiscountRequest.FromString,
                    response_serializer=FuelDiscounts__pb2.UpdateCarwashFuelDiscountReply.SerializeToString,
            ),
            'DeleteCarwashFuelDiscount': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCarwashFuelDiscount,
                    request_deserializer=FuelDiscounts__pb2.DeleteCarwashFuelDiscountRequest.FromString,
                    response_serializer=FuelDiscounts__pb2.DeleteCarwashFuelDiscountReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FuelDiscounts', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FuelDiscounts(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetManualFuelDiscounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FuelDiscounts/GetManualFuelDiscounts',
            FuelDiscounts__pb2.GetManualFuelDiscountsRequest.SerializeToString,
            FuelDiscounts__pb2.GetManualFuelDiscountsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddManualFuelDiscount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FuelDiscounts/AddManualFuelDiscount',
            FuelDiscounts__pb2.AddManualFuelDiscountRequest.SerializeToString,
            FuelDiscounts__pb2.AddManualFuelDiscountReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateManualFuelDiscount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FuelDiscounts/UpdateManualFuelDiscount',
            FuelDiscounts__pb2.UpdateManualFuelDiscountRequest.SerializeToString,
            FuelDiscounts__pb2.UpdateManualFuelDiscountReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteManualFuelDiscount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FuelDiscounts/DeleteManualFuelDiscount',
            FuelDiscounts__pb2.DeleteManualFuelDiscountRequest.SerializeToString,
            FuelDiscounts__pb2.DeleteManualFuelDiscountReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCashFuelDiscounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FuelDiscounts/GetCashFuelDiscounts',
            FuelDiscounts__pb2.GetCashFuelDiscountsRequest.SerializeToString,
            FuelDiscounts__pb2.GetCashFuelDiscountsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddCashFuelDiscount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FuelDiscounts/AddCashFuelDiscount',
            FuelDiscounts__pb2.AddCashFuelDiscountRequest.SerializeToString,
            FuelDiscounts__pb2.AddCashFuelDiscountReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateCashFuelDiscount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FuelDiscounts/UpdateCashFuelDiscount',
            FuelDiscounts__pb2.UpdateCashFuelDiscountRequest.SerializeToString,
            FuelDiscounts__pb2.UpdateCashFuelDiscountReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteCashFuelDiscount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FuelDiscounts/DeleteCashFuelDiscount',
            FuelDiscounts__pb2.DeleteCashFuelDiscountRequest.SerializeToString,
            FuelDiscounts__pb2.DeleteCashFuelDiscountReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFuelDiscountGroups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FuelDiscounts/GetFuelDiscountGroups',
            FuelDiscounts__pb2.GetFuelDiscountGroupsRequest.SerializeToString,
            FuelDiscounts__pb2.GetFuelDiscountGroupsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddFuelDiscountGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FuelDiscounts/AddFuelDiscountGroup',
            FuelDiscounts__pb2.AddFuelDiscountGroupRequest.SerializeToString,
            FuelDiscounts__pb2.AddFuelDiscountGroupReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateFuelDiscountGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FuelDiscounts/UpdateFuelDiscountGroup',
            FuelDiscounts__pb2.UpdateFuelDiscountGroupRequest.SerializeToString,
            FuelDiscounts__pb2.UpdateFuelDiscountGroupReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteFuelDiscountGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FuelDiscounts/DeleteFuelDiscountGroup',
            FuelDiscounts__pb2.DeleteFuelDiscountGroupRequest.SerializeToString,
            FuelDiscounts__pb2.DeleteFuelDiscountGroupReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCarwashFuelDiscounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FuelDiscounts/GetCarwashFuelDiscounts',
            FuelDiscounts__pb2.GetCarwashFuelDiscountsRequest.SerializeToString,
            FuelDiscounts__pb2.GetCarwashFuelDiscountsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddCarwashFuelDiscount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FuelDiscounts/AddCarwashFuelDiscount',
            FuelDiscounts__pb2.AddCarwashFuelDiscountRequest.SerializeToString,
            FuelDiscounts__pb2.AddCarwashFuelDiscountReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateCarwashFuelDiscount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FuelDiscounts/UpdateCarwashFuelDiscount',
            FuelDiscounts__pb2.UpdateCarwashFuelDiscountRequest.SerializeToString,
            FuelDiscounts__pb2.UpdateCarwashFuelDiscountReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteCarwashFuelDiscount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FuelDiscounts/DeleteCarwashFuelDiscount',
            FuelDiscounts__pb2.DeleteCarwashFuelDiscountRequest.SerializeToString,
            FuelDiscounts__pb2.DeleteCarwashFuelDiscountReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
