# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import libs.grpc.resources.compiled_protos.Store_pb2 as Store__pb2


class StoreServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStoreOptions = channel.unary_unary(
                '/StoreService/GetStoreOptions',
                request_serializer=Store__pb2.GetStoreOptionsRequest.SerializeToString,
                response_deserializer=Store__pb2.GetStoreOptionsReply.FromString,
                )
        self.SetStoreOptions = channel.unary_unary(
                '/StoreService/SetStoreOptions',
                request_serializer=Store__pb2.SetStoreOptionsRequest.SerializeToString,
                response_deserializer=Store__pb2.SetStoreOptionsReply.FromString,
                )
        self.GetDonationConfiguration = channel.unary_unary(
                '/StoreService/GetDonationConfiguration',
                request_serializer=Store__pb2.GetDonationConfigurationRequest.SerializeToString,
                response_deserializer=Store__pb2.GetDonationConfigurationReply.FromString,
                )
        self.SetDonationConfiguration = channel.unary_unary(
                '/StoreService/SetDonationConfiguration',
                request_serializer=Store__pb2.SetDonationConfigurationRequest.SerializeToString,
                response_deserializer=Store__pb2.SetDonationConfigurationReply.FromString,
                )
        self.GetAccountingOptions = channel.unary_unary(
                '/StoreService/GetAccountingOptions',
                request_serializer=Store__pb2.GetAccountingOptionsRequest.SerializeToString,
                response_deserializer=Store__pb2.GetAccountingOptionsReply.FromString,
                )
        self.SetAccountingOptions = channel.unary_unary(
                '/StoreService/SetAccountingOptions',
                request_serializer=Store__pb2.SetAccountingOptionsRequest.SerializeToString,
                response_deserializer=Store__pb2.SetAccountingOptionsReply.FromString,
                )
        self.GetInsite360Configuration = channel.unary_unary(
                '/StoreService/GetInsite360Configuration',
                request_serializer=Store__pb2.GetInsite360ConfigurationRequest.SerializeToString,
                response_deserializer=Store__pb2.GetInsite360ConfigurationReply.FromString,
                )
        self.SetInsite360Configuration = channel.unary_unary(
                '/StoreService/SetInsite360Configuration',
                request_serializer=Store__pb2.SetInsite360ConfigurationRequest.SerializeToString,
                response_deserializer=Store__pb2.SetInsite360ConfigurationReply.FromString,
                )
        self.GetSystemRecoveryConfiguration = channel.unary_unary(
                '/StoreService/GetSystemRecoveryConfiguration',
                request_serializer=Store__pb2.GetSystemRecoveryConfigurationRequest.SerializeToString,
                response_deserializer=Store__pb2.GetSystemRecoveryConfigurationReply.FromString,
                )
        self.SetSystemRecoveryConfiguration = channel.unary_unary(
                '/StoreService/SetSystemRecoveryConfiguration',
                request_serializer=Store__pb2.SetSystemRecoveryConfigurationRequest.SerializeToString,
                response_deserializer=Store__pb2.SetSystemRecoveryConfigurationReply.FromString,
                )
        self.AddIncomeExpenseAccount = channel.unary_unary(
                '/StoreService/AddIncomeExpenseAccount',
                request_serializer=Store__pb2.AddIncomeExpenseAccountRequest.SerializeToString,
                response_deserializer=Store__pb2.AddIncomeExpenseAccountReply.FromString,
                )
        self.GetIncomeExpenseAccounts = channel.unary_unary(
                '/StoreService/GetIncomeExpenseAccounts',
                request_serializer=Store__pb2.GetIncomeExpenseAccountsRequest.SerializeToString,
                response_deserializer=Store__pb2.GetIncomeExpenseAccountsReply.FromString,
                )
        self.UpdateIncomeExpenseAccount = channel.unary_unary(
                '/StoreService/UpdateIncomeExpenseAccount',
                request_serializer=Store__pb2.UpdateIncomeExpenseAccountRequest.SerializeToString,
                response_deserializer=Store__pb2.UpdateIncomeExpenseAccountReply.FromString,
                )
        self.DeleteIncomeExpenseAccount = channel.unary_unary(
                '/StoreService/DeleteIncomeExpenseAccount',
                request_serializer=Store__pb2.DeleteIncomeExpenseAccountRequest.SerializeToString,
                response_deserializer=Store__pb2.DeleteIncomeExpenseAccountReply.FromString,
                )


class StoreServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStoreOptions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetStoreOptions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDonationConfiguration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDonationConfiguration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountingOptions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAccountingOptions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInsite360Configuration(self, request, context):
        """move to I360 service itself
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetInsite360Configuration(self, request, context):
        """rpc RegisterSite (RegisterSiteRequest) returns (RegisterSiteReply);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemRecoveryConfiguration(self, request, context):
        """recovery
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSystemRecoveryConfiguration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddIncomeExpenseAccount(self, request, context):
        """Local Accounts Maintenance

        Income/Expense Account Maintenance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIncomeExpenseAccounts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateIncomeExpenseAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteIncomeExpenseAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStoreOptions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStoreOptions,
                    request_deserializer=Store__pb2.GetStoreOptionsRequest.FromString,
                    response_serializer=Store__pb2.GetStoreOptionsReply.SerializeToString,
            ),
            'SetStoreOptions': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStoreOptions,
                    request_deserializer=Store__pb2.SetStoreOptionsRequest.FromString,
                    response_serializer=Store__pb2.SetStoreOptionsReply.SerializeToString,
            ),
            'GetDonationConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDonationConfiguration,
                    request_deserializer=Store__pb2.GetDonationConfigurationRequest.FromString,
                    response_serializer=Store__pb2.GetDonationConfigurationReply.SerializeToString,
            ),
            'SetDonationConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDonationConfiguration,
                    request_deserializer=Store__pb2.SetDonationConfigurationRequest.FromString,
                    response_serializer=Store__pb2.SetDonationConfigurationReply.SerializeToString,
            ),
            'GetAccountingOptions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountingOptions,
                    request_deserializer=Store__pb2.GetAccountingOptionsRequest.FromString,
                    response_serializer=Store__pb2.GetAccountingOptionsReply.SerializeToString,
            ),
            'SetAccountingOptions': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAccountingOptions,
                    request_deserializer=Store__pb2.SetAccountingOptionsRequest.FromString,
                    response_serializer=Store__pb2.SetAccountingOptionsReply.SerializeToString,
            ),
            'GetInsite360Configuration': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInsite360Configuration,
                    request_deserializer=Store__pb2.GetInsite360ConfigurationRequest.FromString,
                    response_serializer=Store__pb2.GetInsite360ConfigurationReply.SerializeToString,
            ),
            'SetInsite360Configuration': grpc.unary_unary_rpc_method_handler(
                    servicer.SetInsite360Configuration,
                    request_deserializer=Store__pb2.SetInsite360ConfigurationRequest.FromString,
                    response_serializer=Store__pb2.SetInsite360ConfigurationReply.SerializeToString,
            ),
            'GetSystemRecoveryConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemRecoveryConfiguration,
                    request_deserializer=Store__pb2.GetSystemRecoveryConfigurationRequest.FromString,
                    response_serializer=Store__pb2.GetSystemRecoveryConfigurationReply.SerializeToString,
            ),
            'SetSystemRecoveryConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSystemRecoveryConfiguration,
                    request_deserializer=Store__pb2.SetSystemRecoveryConfigurationRequest.FromString,
                    response_serializer=Store__pb2.SetSystemRecoveryConfigurationReply.SerializeToString,
            ),
            'AddIncomeExpenseAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.AddIncomeExpenseAccount,
                    request_deserializer=Store__pb2.AddIncomeExpenseAccountRequest.FromString,
                    response_serializer=Store__pb2.AddIncomeExpenseAccountReply.SerializeToString,
            ),
            'GetIncomeExpenseAccounts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIncomeExpenseAccounts,
                    request_deserializer=Store__pb2.GetIncomeExpenseAccountsRequest.FromString,
                    response_serializer=Store__pb2.GetIncomeExpenseAccountsReply.SerializeToString,
            ),
            'UpdateIncomeExpenseAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateIncomeExpenseAccount,
                    request_deserializer=Store__pb2.UpdateIncomeExpenseAccountRequest.FromString,
                    response_serializer=Store__pb2.UpdateIncomeExpenseAccountReply.SerializeToString,
            ),
            'DeleteIncomeExpenseAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteIncomeExpenseAccount,
                    request_deserializer=Store__pb2.DeleteIncomeExpenseAccountRequest.FromString,
                    response_serializer=Store__pb2.DeleteIncomeExpenseAccountReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'StoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StoreService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStoreOptions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StoreService/GetStoreOptions',
            Store__pb2.GetStoreOptionsRequest.SerializeToString,
            Store__pb2.GetStoreOptionsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetStoreOptions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StoreService/SetStoreOptions',
            Store__pb2.SetStoreOptionsRequest.SerializeToString,
            Store__pb2.SetStoreOptionsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDonationConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StoreService/GetDonationConfiguration',
            Store__pb2.GetDonationConfigurationRequest.SerializeToString,
            Store__pb2.GetDonationConfigurationReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetDonationConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StoreService/SetDonationConfiguration',
            Store__pb2.SetDonationConfigurationRequest.SerializeToString,
            Store__pb2.SetDonationConfigurationReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAccountingOptions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StoreService/GetAccountingOptions',
            Store__pb2.GetAccountingOptionsRequest.SerializeToString,
            Store__pb2.GetAccountingOptionsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetAccountingOptions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StoreService/SetAccountingOptions',
            Store__pb2.SetAccountingOptionsRequest.SerializeToString,
            Store__pb2.SetAccountingOptionsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetInsite360Configuration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StoreService/GetInsite360Configuration',
            Store__pb2.GetInsite360ConfigurationRequest.SerializeToString,
            Store__pb2.GetInsite360ConfigurationReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetInsite360Configuration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StoreService/SetInsite360Configuration',
            Store__pb2.SetInsite360ConfigurationRequest.SerializeToString,
            Store__pb2.SetInsite360ConfigurationReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSystemRecoveryConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StoreService/GetSystemRecoveryConfiguration',
            Store__pb2.GetSystemRecoveryConfigurationRequest.SerializeToString,
            Store__pb2.GetSystemRecoveryConfigurationReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetSystemRecoveryConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StoreService/SetSystemRecoveryConfiguration',
            Store__pb2.SetSystemRecoveryConfigurationRequest.SerializeToString,
            Store__pb2.SetSystemRecoveryConfigurationReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddIncomeExpenseAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StoreService/AddIncomeExpenseAccount',
            Store__pb2.AddIncomeExpenseAccountRequest.SerializeToString,
            Store__pb2.AddIncomeExpenseAccountReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetIncomeExpenseAccounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StoreService/GetIncomeExpenseAccounts',
            Store__pb2.GetIncomeExpenseAccountsRequest.SerializeToString,
            Store__pb2.GetIncomeExpenseAccountsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateIncomeExpenseAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StoreService/UpdateIncomeExpenseAccount',
            Store__pb2.UpdateIncomeExpenseAccountRequest.SerializeToString,
            Store__pb2.UpdateIncomeExpenseAccountReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteIncomeExpenseAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StoreService/DeleteIncomeExpenseAccount',
            Store__pb2.DeleteIncomeExpenseAccountRequest.SerializeToString,
            Store__pb2.DeleteIncomeExpenseAccountReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
